---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/azure-cpi-release}

inputs:
  - name: bosh-cpi-src

run:
  path: bosh-cpi-src/ci/tasks/azure-provision.sh

params:
  AZURE_CLIENT_ID:                            ""
  AZURE_CLIENT_SECRET:                        ""
  AZURE_TENANT_ID:                            ""
  AZURE_GROUP_NAME_FOR_VMS:                   ""
  AZURE_GROUP_NAME_FOR_NETWORK:               ""
  AZURE_GROUP_NAME_FOR_VMS_MANAGED_DISKS:     ""
  AZURE_GROUP_NAME_FOR_NETWORK_MANAGED_DISKS: ""
  AZURE_GROUP_NAME_FOR_VMS_CENTOS:            ""
  AZURE_GROUP_NAME_FOR_NETWORK_CENTOS:        ""
  AZURE_REGION_NAME:                          ""
  AZURE_REGION_SHORT_NAME:                    ""
  AZURE_STORAGE_ACCOUNT_NAME:                 ""
  AZURE_STORAGE_ACCOUNT_NAME_MANAGED_DISKS:   ""
  AZURE_VNET_NAME_FOR_BATS:                   ""
  AZURE_VNET_NAME_FOR_LIFECYCLE:              ""
  AUZRE_BOSH_SUBNET_NAME:                     ""
  AUZRE_BOSH_SECOND_SUBNET_NAME:              ""
  AZURE_CF_SUBNET_NAME:                       ""
  AZURE_CF_SECOND_SUBNET_NAME:                ""
