---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/azure-cpi-release}

inputs:
  - name: bosh-cpi-dev-artifacts # -++ used for deployment manifest referenced by manifest_path
  - name: version-semver         # -//
  - name: bosh-cpi-src
  - name: bosh-init              # --- bosh-init executable to do deploy
  - name: bosh-release           # -\
  - name: stemcell

outputs:
  - name: director-state

run:
  path: bosh-cpi-src/ci/tasks/setup-director.sh

params:
  AZURE_CLIENT_ID:              ""
  AZURE_CLIENT_SECRET:          ""
  AZURE_TENANT_ID:              ""
  AZURE_GROUP_NAME_FOR_VMS:     ""
  AZURE_GROUP_NAME_FOR_NETWORK: ""
  AZURE_VNET_NAME_FOR_BATS:     ""
  AZURE_STORAGE_ACCOUNT_NAME:   ""
  AZURE_SUBSCRIPTION_ID:        ""
  AZURE_BOSH_SUBNET_NAME:       ""
  AZURE_DEFAULT_SECURITY_GROUP: ""
  AZURE_DEBUG_MODE:             ""
  AZURE_USE_MANAGED_DISKS:      false
  BAT_NETWORK_GATEWAY:          ""
  BOSH_DIRECTOR_USERNAME:       ""
  BOSH_DIRECTOR_PASSWORD:       ""
  SSH_PUBLIC_KEY:               ""
  SSH_PRIVATE_KEY:              ""
  BOSH_INIT_LOG_LEVEL:          debug
