---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/azure-cpi-release}

inputs:
  - name: bosh-cpi-src
  - name: director-state
  - name: bosh-init

run:
  path: bosh-cpi-src/ci/tasks/teardown-director.sh

params:
  BOSH_INIT_LOG_LEVEL: debug
